# Production Rendezvous Servers
# Deploys multiple rendezvous servers for omerta.run subdomains
#
# CREDENTIALS: AWS credentials are sourced from environment variables:
#   - AWS_ACCESS_KEY_ID
#   - AWS_SECRET_ACCESS_KEY
#   - AWS_REGION (optional, defaults to us-east-1)
#
# See .env.example for required environment variables.

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Uncomment and configure for remote state
  # backend "s3" {
  #   bucket = "omerta-terraform-state"
  #   key    = "prod/rendezvous.tfstate"
  #   region = "us-east-1"
  # }
}

# AWS provider uses credentials from environment variables:
# AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
provider "aws" {
  region = var.aws_region

  # Credentials are read from environment variables automatically.
  # DO NOT hardcode credentials here.
  #
  # The provider checks these sources in order:
  # 1. Environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)
  # 2. Shared credentials file (~/.aws/credentials)
  # 3. IAM role (if running on EC2)
}

# Data sources for default VPC (customize for production)
data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}

# Latest Amazon Linux 2023 AMI
data "aws_ami" "amazon_linux_2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# =============================================================================
# Network Configuration
# =============================================================================
# The omerta:// link is created locally using `omerta network create` and
# passed to Terraform via the TF_VAR_omerta_network_link environment variable.
#
# To create a network:
#   omerta network create --name "omerta-prod" \
#     --bootstrap "rendezvous1.omerta.run:9999" \
#     --bootstrap "rendezvous2.omerta.run:9999"
#
# Then copy the omerta://join/... link and set:
#   export TF_VAR_omerta_network_link="omerta://join/..."

# User data script to install dependencies and set up systemd services
locals {
  user_data = <<-EOF
    #!/bin/bash
    set -e

    # Update system
    dnf update -y

    # Install dependencies
    dnf install -y git gcc-c++ libcurl-devel libuuid-devel libxml2-devel ncurses-devel

    # Create omerta user with home directory
    useradd -r -m -d /home/omerta -s /bin/bash omerta || true

    # Create directories
    mkdir -p /opt/omerta /var/log/omerta /home/omerta/.omerta
    chown -R omerta:omerta /opt/omerta /var/log/omerta /home/omerta/.omerta

    # Configure log rotation to prevent disk from filling up
    cat > /etc/logrotate.d/omerta <<'LOGROTATE'
/var/log/omerta/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
LOGROTATE

    # Write the network join link for first-boot initialization
    # The omerta CLI will use this to join the network
    cat > /home/omerta/.omerta/network-link.txt <<'LINK'
    ${var.omerta_network_link}
    LINK
    chown omerta:omerta /home/omerta/.omerta/network-link.txt

    # Create omertad config file
    # Note: can-relay is false to minimize bandwidth costs.
    # Set can-relay=true if you need to relay data for peers who can't establish direct connections.
    cat > /home/omerta/.omerta/omertad.conf <<'CONFIG'
    # Omerta Daemon Configuration
    # Generated by Terraform

    # Mesh port
    port=9999

    # Relay mode - disabled to minimize bandwidth costs
    # Enable if peers need data relay for connectivity
    can-relay=false

    # Hole punch coordination - enabled for NAT traversal
    can-coordinate-hole-punch=true
    CONFIG
    chown omerta:omerta /home/omerta/.omerta/omertad.conf

    # Create omerta-stun systemd service
    cat > /etc/systemd/system/omerta-stun.service <<'SERVICE'
    [Unit]
    Description=Omerta STUN Server
    After=network.target

    [Service]
    Type=simple
    User=omerta
    Group=omerta
    ExecStart=/opt/omerta/omerta-stun --port 3478 --log-level info
    Restart=always
    RestartSec=5
    StandardOutput=append:/var/log/omerta/stun.log
    StandardError=append:/var/log/omerta/stun.log

    [Install]
    WantedBy=multi-user.target
    SERVICE

    # Create omertad systemd service
    # Note: Network ID will be set after first boot when joining the network
    cat > /etc/systemd/system/omertad.service <<'SERVICE'
    [Unit]
    Description=Omerta Daemon
    After=network.target

    [Service]
    Type=simple
    User=omerta
    Group=omerta
    WorkingDirectory=/home/omerta
    ExecStart=/opt/omerta/omertad start --config /home/omerta/.omerta/omertad.conf
    ExecReload=/opt/omerta/omertad restart --config /home/omerta/.omerta/omertad.conf
    Restart=always
    RestartSec=5
    StandardOutput=append:/var/log/omerta/omertad.log
    StandardError=append:/var/log/omerta/omertad.log

    [Install]
    WantedBy=multi-user.target
    SERVICE

    # Create first-boot script to join the network
    cat > /opt/omerta/first-boot.sh <<'FIRSTBOOT'
    #!/bin/bash
    # First boot: join the omerta network using the provisioned link
    set -e

    LINK_FILE="/home/omerta/.omerta/network-link.txt"
    JOINED_FLAG="/home/omerta/.omerta/.network-joined"

    if [ -f "$JOINED_FLAG" ]; then
        echo "Network already joined, skipping..."
        exit 0
    fi

    if [ ! -f "$LINK_FILE" ]; then
        echo "No network link file found at $LINK_FILE"
        exit 1
    fi

    LINK=$(cat "$LINK_FILE" | tr -d '[:space:]')

    echo "Joining omerta network..."
    /opt/omerta/omerta network join "$LINK"

    # Get the network ID and update config
    NETWORK_ID=$(/opt/omerta/omerta network list --json 2>/dev/null | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)

    if [ -n "$NETWORK_ID" ]; then
        echo "network=$NETWORK_ID" >> /home/omerta/.omerta/omertad.conf
        touch "$JOINED_FLAG"
        echo "Successfully joined network: $NETWORK_ID"
    else
        echo "Warning: Could not determine network ID"
    fi
    FIRSTBOOT
    chmod +x /opt/omerta/first-boot.sh
    chown omerta:omerta /opt/omerta/first-boot.sh

    systemctl daemon-reload
    systemctl enable omerta-stun
    systemctl enable omertad

    echo "Setup complete. Deploy binaries to /opt/omerta/ and run first-boot.sh to join the network."
  EOF
}

# Primary rendezvous server
module "rendezvous1" {
  source = "../../modules/rendezvous"

  name          = "omerta-rendezvous1-prod"
  vpc_id        = data.aws_vpc.default.id
  subnet_id     = data.aws_subnets.default.ids[0]
  ami_id        = data.aws_ami.amazon_linux_2023.id
  instance_type = var.instance_type
  key_name      = var.key_name
  volume_size   = 8
  create_eip    = true
  user_data     = local.user_data

  ssh_cidr_blocks = var.ssh_cidr_blocks

  tags = {
    Environment = "prod"
    Service     = "rendezvous"
    Domain      = "rendezvous1.omerta.run"
    Backup      = "true"
  }
}

# Secondary rendezvous server (different AZ for redundancy)
module "rendezvous2" {
  source = "../../modules/rendezvous"

  name          = "omerta-rendezvous2-prod"
  vpc_id        = data.aws_vpc.default.id
  subnet_id     = length(data.aws_subnets.default.ids) > 1 ? data.aws_subnets.default.ids[1] : data.aws_subnets.default.ids[0]
  ami_id        = data.aws_ami.amazon_linux_2023.id
  instance_type = var.instance_type
  key_name      = var.key_name
  volume_size   = 8
  create_eip    = true
  user_data     = local.user_data

  ssh_cidr_blocks = var.ssh_cidr_blocks

  tags = {
    Environment = "prod"
    Service     = "rendezvous"
    Domain      = "rendezvous2.omerta.run"
    Backup      = "true"
  }
}

# =============================================================================
# Route53 DNS Configuration
# =============================================================================

# Create hosted zone for omerta.run
# After creation, update Squarespace nameservers to point to Route53
resource "aws_route53_zone" "omerta" {
  name    = var.domain_name
  comment = "Managed by Terraform - Omerta infrastructure"

  tags = {
    Environment = "prod"
    ManagedBy   = "terraform"
  }
}

# rendezvous1.omerta.run -> Primary rendezvous server
resource "aws_route53_record" "rendezvous1" {
  zone_id = aws_route53_zone.omerta.zone_id
  name    = "rendezvous1.${var.domain_name}"
  type    = "A"
  ttl     = 300
  records = [module.rendezvous1.public_ip]
}

# rendezvous2.omerta.run -> Secondary rendezvous server
resource "aws_route53_record" "rendezvous2" {
  zone_id = aws_route53_zone.omerta.zone_id
  name    = "rendezvous2.${var.domain_name}"
  type    = "A"
  ttl     = 300
  records = [module.rendezvous2.public_ip]
}

# stun1.omerta.run -> Alias to rendezvous1 (for STUN-specific endpoint)
resource "aws_route53_record" "stun1" {
  zone_id = aws_route53_zone.omerta.zone_id
  name    = "stun1.${var.domain_name}"
  type    = "A"
  ttl     = 300
  records = [module.rendezvous1.public_ip]
}

# stun2.omerta.run -> Alias to rendezvous2 (for STUN-specific endpoint)
resource "aws_route53_record" "stun2" {
  zone_id = aws_route53_zone.omerta.zone_id
  name    = "stun2.${var.domain_name}"
  type    = "A"
  ttl     = 300
  records = [module.rendezvous2.public_ip]
}

# =============================================================================
# CloudWatch Bandwidth Monitoring & Alerts
# =============================================================================

# SNS topic for alerts (only created if alert_email is provided)
resource "aws_sns_topic" "bandwidth_alerts" {
  count = var.alert_email != "" ? 1 : 0
  name  = "omerta-bandwidth-alerts"

  tags = {
    Environment = "prod"
    ManagedBy   = "terraform"
  }
}

resource "aws_sns_topic_subscription" "bandwidth_alerts_email" {
  count     = var.alert_email != "" ? 1 : 0
  topic_arn = aws_sns_topic.bandwidth_alerts[0].arn
  protocol  = "email"
  endpoint  = var.alert_email
}

# Calculate threshold: 80% of monthly cap, converted to bytes per 5-minute period
# Monthly cap (GB) * 0.8 * 1024^3 / (30 days * 24 hours * 12 periods/hour)
locals {
  # Bytes per 5-minute period at 80% of monthly cap
  bandwidth_threshold_bytes = var.bandwidth_cap_gb * 0.8 * 1073741824 / (30 * 24 * 12)
}

# Bandwidth alarm for rendezvous1
resource "aws_cloudwatch_metric_alarm" "rendezvous1_bandwidth" {
  alarm_name          = "omerta-rendezvous1-bandwidth-warning"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 3
  metric_name         = "NetworkOut"
  namespace           = "AWS/EC2"
  period              = 300  # 5 minutes
  statistic           = "Sum"
  threshold           = local.bandwidth_threshold_bytes
  alarm_description   = "Bandwidth usage exceeding 80% of ${var.bandwidth_cap_gb}GB monthly cap"
  treat_missing_data  = "notBreaching"

  dimensions = {
    InstanceId = module.rendezvous1.instance_id
  }

  # Only send to SNS if email is configured
  alarm_actions = var.alert_email != "" ? [aws_sns_topic.bandwidth_alerts[0].arn] : []
  ok_actions    = var.alert_email != "" ? [aws_sns_topic.bandwidth_alerts[0].arn] : []

  tags = {
    Environment = "prod"
    Service     = "rendezvous"
  }
}

# Bandwidth alarm for rendezvous2
resource "aws_cloudwatch_metric_alarm" "rendezvous2_bandwidth" {
  alarm_name          = "omerta-rendezvous2-bandwidth-warning"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 3
  metric_name         = "NetworkOut"
  namespace           = "AWS/EC2"
  period              = 300  # 5 minutes
  statistic           = "Sum"
  threshold           = local.bandwidth_threshold_bytes
  alarm_description   = "Bandwidth usage exceeding 80% of ${var.bandwidth_cap_gb}GB monthly cap"
  treat_missing_data  = "notBreaching"

  dimensions = {
    InstanceId = module.rendezvous2.instance_id
  }

  alarm_actions = var.alert_email != "" ? [aws_sns_topic.bandwidth_alerts[0].arn] : []
  ok_actions    = var.alert_email != "" ? [aws_sns_topic.bandwidth_alerts[0].arn] : []

  tags = {
    Environment = "prod"
    Service     = "rendezvous"
  }
}

# =============================================================================
# EBS Snapshot Automation (Data Lifecycle Manager)
# =============================================================================
# Automated daily snapshots of bootstrap node EBS volumes for disaster recovery.
# Identity attestation data and configuration are preserved in these snapshots.

# IAM role for DLM
resource "aws_iam_role" "dlm_lifecycle_role" {
  count = var.enable_ebs_snapshots ? 1 : 0
  name  = "omerta-dlm-lifecycle-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "dlm.amazonaws.com"
        }
      }
    ]
  })

  tags = {
    Environment = "prod"
    ManagedBy   = "terraform"
  }
}

resource "aws_iam_role_policy_attachment" "dlm_lifecycle" {
  count      = var.enable_ebs_snapshots ? 1 : 0
  role       = aws_iam_role.dlm_lifecycle_role[0].name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSDataLifecycleManagerServiceRole"
}

# DLM lifecycle policy for EBS snapshots
resource "aws_dlm_lifecycle_policy" "ebs_snapshots" {
  count       = var.enable_ebs_snapshots ? 1 : 0
  description = "Automated EBS snapshots for Omerta bootstrap nodes"
  state       = "ENABLED"

  execution_role_arn = aws_iam_role.dlm_lifecycle_role[0].arn

  policy_details {
    resource_types = ["INSTANCE"]

    # Target instances with the Backup=true tag
    target_tags = {
      Backup = "true"
    }

    schedule {
      name = "Daily snapshots"

      create_rule {
        cron_expression = var.snapshot_schedule_cron
      }

      retain_rule {
        count = var.snapshot_retention_days
      }

      tags_to_add = {
        SnapshotCreator = "DLM"
        Environment     = "prod"
        Service         = "rendezvous"
      }

      copy_tags = true
    }
  }

  tags = {
    Environment = "prod"
    ManagedBy   = "terraform"
  }
}
